name: FirstTest
favicon: null
layout_spectrum: 0.4756989050656557
typography_spectrum: 0.48759
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0071bd'
    - '#fcfafb'
    - '#71bae1'
    - '#35a7dd'
    - '#d1e6f1'
  brandStrength: 0.120829111430794
  lightness: 0.8505969739053398
  saturation: 0.5625
  rhythmicContrast: 0.26448510377667844
purpose: []
